<?php

namespace Database\Seeders;

use App\Models\TimetableClass;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TimetableClassSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $classes = [
            [
                'id' => 1,
                'user_id' => 1,
                'name' => 'IT就職作品開発',
                'description' => null,
                'room' => '1603',
                'instructor' => '杉原',
                'day' => 'monday',
                'period' => 1,
                'start_time' => '09:15:00',
                'end_time' => '10:45:00',
                'color' => '#4F46E5',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 2,
                'user_id' => 1,
                'name' => 'IT就職作品開発',
                'description' => null,
                'room' => '1603',
                'instructor' => '杉原',
                'day' => 'monday',
                'period' => 2,
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'color' => '#4F46E5',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 3,
                'user_id' => 1,
                'name' => 'AWSクラウド演習',
                'description' => null,
                'room' => '3501',
                'instructor' => '加藤',
                'day' => 'monday',
                'period' => 3,
                'start_time' => '13:30:00',
                'end_time' => '15:00:00',
                'color' => '#8B5CF6',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 4,
                'user_id' => 1,
                'name' => 'AWSクラウド演習',
                'description' => null,
                'room' => '3501',
                'instructor' => '加藤',
                'day' => 'monday',
                'period' => 4,
                'start_time' => '13:15:00',
                'end_time' => '16:45:00',
                'color' => '#4F46E5',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 5,
                'user_id' => 1,
                'name' => 'モバイルアプリ開発演習',
                'description' => null,
                'room' => '1604',
                'instructor' => '良原',
                'day' => 'tuesday',
                'period' => 1,
                'start_time' => '09:15:00',
                'end_time' => '10:45:00',
                'color' => '#10B981',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 6,
                'user_id' => 1,
                'name' => 'モバイルアプリ開発演習',
                'description' => null,
                'room' => '1604',
                'instructor' => '良原',
                'day' => 'tuesday',
                'period' => 2,
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'color' => '#4F46E5',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 7,
                'user_id' => 1,
                'name' => 'モバイルアプリ開発演習',
                'description' => null,
                'room' => '1604',
                'instructor' => '良原',
                'day' => 'tuesday',
                'period' => 2,
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'color' => '#10B981',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 8,
                'user_id' => 1,
                'name' => 'AWSクラウド演習',
                'description' => null,
                'room' => '3501',
                'instructor' => '加藤',
                'day' => 'monday',
                'period' => 4,
                'start_time' => '15:15:00',
                'end_time' => '16:45:00',
                'color' => '#8B5CF6',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 9,
                'user_id' => 1,
                'name' => 'AI活用演習',
                'description' => null,
                'room' => '1604',
                'instructor' => '良原',
                'day' => 'tuesday',
                'period' => 3,
                'start_time' => '13:30:00',
                'end_time' => '15:00:00',
                'color' => '#F59E0B',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 10,
                'user_id' => 1,
                'name' => 'AI活用演習',
                'description' => null,
                'room' => '1604',
                'instructor' => '良原',
                'day' => 'tuesday',
                'period' => 4,
                'start_time' => '15:15:00',
                'end_time' => '16:45:00',
                'color' => '#F59E0B',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 11,
                'user_id' => 1,
                'name' => 'AI活用演習',
                'description' => null,
                'room' => '1604',
                'instructor' => '良原',
                'day' => 'tuesday',
                'period' => 3,
                'start_time' => '13:30:00',
                'end_time' => '15:00:00',
                'color' => '#4F46E5',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 12,
                'user_id' => 1,
                'name' => 'AI活用演習',
                'description' => null,
                'room' => '1604',
                'instructor' => '良原',
                'day' => 'tuesday',
                'period' => 3,
                'start_time' => '13:30:00',
                'end_time' => '15:00:00',
                'color' => '#F59E0B',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 13,
                'user_id' => 1,
                'name' => 'IoT制作演習Ⅰ',
                'description' => null,
                'room' => '3501',
                'instructor' => '藤原',
                'day' => 'wednesday',
                'period' => 1,
                'start_time' => '09:15:00',
                'end_time' => '10:45:00',
                'color' => '#EF4444',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 14,
                'user_id' => 1,
                'name' => 'IoT制作演習Ⅰ',
                'description' => null,
                'room' => '3501',
                'instructor' => '藤原',
                'day' => 'wednesday',
                'period' => 2,
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'color' => '#EF4444',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 15,
                'user_id' => 1,
                'name' => '外国語Ⅳ',
                'description' => null,
                'room' => '1302',
                'instructor' => null,
                'day' => 'thursday',
                'period' => 1,
                'start_time' => '09:15:00',
                'end_time' => '10:45:00',
                'color' => '#4F46E5',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 16,
                'user_id' => 1,
                'name' => '就職対策',
                'description' => null,
                'room' => '3303',
                'instructor' => '高橋',
                'day' => 'thursday',
                'period' => 2,
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'color' => '#8B5CF6',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 17,
                'user_id' => 1,
                'name' => 'IT就職作品開発',
                'description' => null,
                'room' => '1603',
                'instructor' => '良原',
                'day' => 'thursday',
                'period' => 3,
                'start_time' => '13:30:00',
                'end_time' => '15:00:00',
                'color' => '#4F46E5',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 18,
                'user_id' => 1,
                'name' => 'IT就職作品開発',
                'description' => null,
                'room' => '1603',
                'instructor' => '良原',
                'day' => 'thursday',
                'period' => 4,
                'start_time' => '15:15:00',
                'end_time' => '16:45:00',
                'color' => '#4F46E5',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 19,
                'user_id' => 1,
                'name' => 'デスクトップアプリ開発',
                'description' => null,
                'room' => '2301',
                'instructor' => '細井',
                'day' => 'friday',
                'period' => 3,
                'start_time' => '13:30:00',
                'end_time' => '15:00:00',
                'color' => '#10B981',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 20,
                'user_id' => 1,
                'name' => 'デスクトップアプリ開発',
                'description' => null,
                'room' => '2301',
                'instructor' => '細井',
                'day' => 'friday',
                'period' => 4,
                'start_time' => '15:15:00',
                'end_time' => '16:45:00',
                'color' => '#10B981',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
            [
                'id' => 21,
                'user_id' => 1,
                'name' => 'AI活用演習',
                'description' => null,
                'room' => '1604',
                'instructor' => '良原',
                'day' => 'tuesday',
                'period' => 3,
                'start_time' => '13:30:00',
                'end_time' => '15:00:00',
                'color' => '#F59E0B',
                'icon' => null,
                'notes' => null,
                'learning_path_id' => null,
            ],
        ];

        // Use DB::table to insert with specific IDs
        foreach ($classes as $class) {
            DB::table('timetable_classes')->insert($class);
        }
    }
}

